import { HEIGHT, WIDTH } from '../../util/constants';
import type { LevelDefinition } from './types';

// Helper to calculate relative positions (2x scale)
const cx = (percent: number) => Math.floor((WIDTH * percent) / 100);
const cy = (percent: number) => Math.floor((HEIGHT * percent) / 100);

// 2x size multiplier for all objects
const SCALE = 2;

export const LEVELS: LevelDefinition[] = [
  {
    id: 1,
    name: 'The First Fall',
    description: 'Easy introduction. Jump across platforms.',
    start: { x: cx(10), y: cy(70) },
    goal: { x: cx(85), y: cy(70) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(80), w: cx(15), h: 40 },
      { type: 'platform', x: cx(25), y: cy(75), w: cx(15), h: 40 },
      { type: 'platform', x: cx(45), y: cy(70), w: cx(15), h: 40 },
      { type: 'platform', x: cx(65), y: cy(75), w: cx(15), h: 40 },
      { type: 'platform', x: cx(82), y: cy(80), w: cx(15), h: 40 },
    ],
  },

  {
    id: 2,
    name: 'Spiky Situation',
    description: 'Avoid the spikes below!',
    start: { x: cx(10), y: cy(60) },
    goal: { x: cx(85), y: cy(60) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(70), w: cx(20), h: 40 },
      { type: 'spikes', x: cx(28), y: cy(90), count: 10, size: 40 },
      { type: 'platform', x: cx(40), y: cy(75), w: cx(12), h: 40 },
      { type: 'platform', x: cx(55), y: cy(70), w: cx(15), h: 40 },
      { type: 'platform', x: cx(75), y: cy(70), w: cx(20), h: 40 },
    ],
  },

  {
    id: 3,
    name: 'Lava Pit',
    description: 'Do not touch the lava!',
    start: { x: cx(10), y: cy(50) },
    goal: { x: cx(85), y: cy(50) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(65), w: cx(15), h: 40 },
      { type: 'lava', x: cx(22), y: cy(82), w: cx(56), h: cy(18) },
      { type: 'platform', x: cx(28), y: cy(58), w: cx(10), h: 40 },
      { type: 'platform', x: cx(43), y: cy(55), w: cx(10), h: 40 },
      { type: 'platform', x: cx(58), y: cy(58), w: cx(10), h: 40 },
      { type: 'platform', x: cx(80), y: cy(65), w: cx(15), h: 40 },
    ],
  },

  {
    id: 4,
    name: 'Laser Gates',
    description: 'Time your jumps through the lasers.',
    start: { x: cx(10), y: cy(70) },
    goal: { x: cx(85), y: cy(70) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(80), w: cx(18), h: 40 },
      {
        type: 'laser',
        x: cx(28),
        y: cy(25),
        w: 20,
        h: cy(55),
        delay: 0,
      },
      { type: 'platform', x: cx(33), y: cy(80), w: cx(12), h: 40 },
      {
        type: 'laser',
        x: cx(50),
        y: cy(25),
        w: 20,
        h: cy(55),
        delay: 600,
      },
      { type: 'platform', x: cx(55), y: cy(80), w: cx(12), h: 40 },
      {
        type: 'laser',
        x: cx(72),
        y: cy(25),
        w: 20,
        h: cy(55),
        delay: 1200,
      },
      { type: 'platform', x: cx(77), y: cy(80), w: cx(18), h: 40 },
    ],
  },

  {
    id: 5,
    name: 'Moving Danger',
    description: 'Watch out for patrolling enemies!',
    start: { x: cx(10), y: cy(65) },
    goal: { x: cx(85), y: cy(65) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(75), w: cx(90), h: 40 },
      {
        type: 'movingEnemy',
        x: cx(25),
        y: cy(58),
        w: 60,
        h: 60,
        range: cx(20),
        speed: 100,
      },
      {
        type: 'movingEnemy',
        x: cx(55),
        y: cy(58),
        w: 60,
        h: 60,
        range: cx(18),
        speed: 120,
      },
      { type: 'spikes', x: cx(15), y: cy(92), count: 5, size: 40 },
      { type: 'spikes', x: cx(70), y: cy(92), count: 5, size: 40 },
    ],
  },

  {
    id: 6,
    name: 'The Gauntlet',
    description: 'Multiple hazards ahead.',
    start: { x: cx(10), y: cy(55) },
    goal: { x: cx(85), y: cy(55) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(65), w: cx(15), h: 40 },
      { type: 'spikes', x: cx(22), y: cy(90), count: 8, size: 40 },
      { type: 'platform', x: cx(30), y: cy(72), w: cx(10), h: 40 },
      {
        type: 'laser',
        x: cx(45),
        y: cy(20),
        w: 20,
        h: cy(65),
        delay: 300,
      },
      { type: 'platform', x: cx(50), y: cy(70), w: cx(10), h: 40 },
      {
        type: 'movingEnemy',
        x: cx(63),
        y: cy(60),
        w: 60,
        h: 60,
        range: cx(12),
        speed: 130,
      },
      { type: 'lava', x: cx(72), y: cy(85), w: cx(10), h: cy(15) },
      { type: 'platform', x: cx(80), y: cy(65), w: cx(15), h: 40 },
    ],
  },

  {
    id: 7,
    name: 'Sky Platforms',
    description: 'Jump high!',
    start: { x: cx(10), y: cy(80) },
    goal: { x: cx(85), y: cy(25) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(85), w: cx(15), h: 40 },
      { type: 'platform', x: cx(23), y: cy(72), w: cx(10), h: 40 },
      { type: 'spikes', x: cx(35), y: cy(92), count: 6, size: 40 },
      { type: 'platform', x: cx(40), y: cy(58), w: cx(10), h: 40 },
      {
        type: 'laser',
        x: cx(54),
        y: cy(10),
        w: 20,
        h: cy(70),
        delay: 500,
      },
      { type: 'platform', x: cx(59), y: cy(44), w: cx(10), h: 40 },
      { type: 'platform', x: cx(75), y: cy(30), w: cx(15), h: 40 },
    ],
  },

  {
    id: 8,
    name: 'Double Trouble',
    description: 'Two lasers, narrow timing.',
    start: { x: cx(10), y: cy(70) },
    goal: { x: cx(85), y: cy(70) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(80), w: cx(20), h: 40 },
      {
        type: 'laser',
        x: cx(30),
        y: cy(15),
        w: 20,
        h: cy(65),
        delay: 0,
      },
      {
        type: 'laser',
        x: cx(48),
        y: cy(15),
        w: 20,
        h: cy(65),
        delay: 450,
      },
      { type: 'platform', x: cx(38), y: cy(80), w: cx(8), h: 40 },
      {
        type: 'laser',
        x: cx(66),
        y: cy(15),
        w: 20,
        h: cy(65),
        delay: 900,
      },
      { type: 'platform', x: cx(56), y: cy(80), w: cx(8), h: 40 },
      { type: 'platform', x: cx(75), y: cy(80), w: cx(20), h: 40 },
    ],
  },

  {
    id: 9,
    name: 'Enemy Swarm',
    description: 'Navigate through multiple enemies.',
    start: { x: cx(10), y: cy(70) },
    goal: { x: cx(85), y: cy(70) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(80), w: cx(90), h: 40 },
      {
        type: 'movingEnemy',
        x: cx(22),
        y: cy(63),
        w: 60,
        h: 60,
        range: cx(12),
        speed: 140,
      },
      {
        type: 'movingEnemy',
        x: cx(42),
        y: cy(63),
        w: 60,
        h: 60,
        range: cx(15),
        speed: 120,
      },
      {
        type: 'movingEnemy',
        x: cx(62),
        y: cy(63),
        w: 60,
        h: 60,
        range: cx(12),
        speed: 150,
      },
      { type: 'spikes', x: cx(35), y: cy(92), count: 4, size: 40 },
      { type: 'spikes', x: cx(70), y: cy(92), count: 4, size: 40 },
    ],
  },

  {
    id: 10,
    name: 'Precision Jump',
    description: 'Small platforms, big gaps.',
    start: { x: cx(10), y: cy(70) },
    goal: { x: cx(85), y: cy(70) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(80), w: cx(10), h: 40 },
      { type: 'platform', x: cx(26), y: cy(75), w: cx(7), h: 40 },
      { type: 'platform', x: cx(46), y: cy(70), w: cx(7), h: 40 },
      { type: 'platform', x: cx(66), y: cy(75), w: cx(7), h: 40 },
      { type: 'platform', x: cx(83), y: cy(80), w: cx(10), h: 40 },
      { type: 'lava', x: 0, y: cy(90), w: WIDTH, h: cy(10) },
    ],
  },

  {
    id: 11,
    name: 'The Descent',
    description: 'Go down carefully.',
    start: { x: cx(10), y: cy(25) },
    goal: { x: cx(85), y: cy(75) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(30), w: cx(15), h: 40 },
      { type: 'platform', x: cx(23), y: cy(42), w: cx(10), h: 40 },
      {
        type: 'laser',
        x: cx(38),
        y: cy(50),
        w: 20,
        h: cy(35),
        delay: 400,
      },
      { type: 'platform', x: cx(43), y: cy(54), w: cx(10), h: 40 },
      { type: 'spikes', x: cx(55), y: cy(92), count: 6, size: 40 },
      { type: 'platform', x: cx(63), y: cy(66), w: cx(10), h: 40 },
      {
        type: 'movingEnemy',
        x: cx(78),
        y: cy(70),
        w: 60,
        h: 60,
        range: cx(10),
        speed: 110,
      },
      { type: 'platform', x: cx(83), y: cy(82), w: cx(12), h: 40 },
    ],
  },

  {
    id: 12,
    name: 'Laser Maze',
    description: 'Multiple timed lasers.',
    start: { x: cx(10), y: cy(70) },
    goal: { x: cx(85), y: cy(70) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(80), w: cx(13), h: 40 },
      {
        type: 'laser',
        x: cx(23),
        y: cy(20),
        w: 20,
        h: cy(60),
        delay: 0,
      },
      { type: 'platform', x: cx(28), y: cy(80), w: cx(10), h: 40 },
      {
        type: 'laser',
        x: cx(43),
        y: cy(20),
        w: 20,
        h: cy(60),
        delay: 400,
      },
      { type: 'platform', x: cx(48), y: cy(80), w: cx(10), h: 40 },
      {
        type: 'laser',
        x: cx(63),
        y: cy(20),
        w: 20,
        h: cy(60),
        delay: 800,
      },
      { type: 'platform', x: cx(68), y: cy(80), w: cx(10), h: 40 },
      { type: 'spikes', x: cx(38), y: cy(92), count: 3, size: 40 },
      { type: 'spikes', x: cx(58), y: cy(92), count: 3, size: 40 },
      { type: 'platform', x: cx(82), y: cy(80), w: cx(13), h: 40 },
    ],
  },

  {
    id: 13,
    name: 'Chaos Rising',
    description: 'Everything at once!',
    start: { x: cx(10), y: cy(65) },
    goal: { x: cx(85), y: cy(35) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(75), w: cx(13), h: 40 },
      { type: 'spikes', x: cx(20), y: cy(92), count: 5, size: 40 },
      { type: 'platform', x: cx(28), y: cy(70), w: cx(10), h: 40 },
      {
        type: 'movingEnemy',
        x: cx(43),
        y: cy(63),
        w: 60,
        h: 60,
        range: cx(12),
        speed: 130,
      },
      {
        type: 'laser',
        x: cx(56),
        y: cy(15),
        w: 20,
        h: cy(65),
        delay: 250,
      },
      { type: 'platform', x: cx(61), y: cy(55), w: cx(10), h: 40 },
      { type: 'lava', x: cx(73), y: cy(85), w: cx(10), h: cy(15) },
      { type: 'platform', x: cx(78), y: cy(40), w: cx(15), h: 40 },
    ],
  },

  {
    id: 14,
    name: 'The Trial',
    description: 'Almost there...',
    start: { x: cx(10), y: cy(75) },
    goal: { x: cx(85), y: cy(30) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(82), w: cx(13), h: 40 },
      { type: 'lava', x: cx(20), y: cy(88), w: cx(20), h: cy(12) },
      { type: 'platform', x: cx(26), y: cy(70), w: cx(8), h: 40 },
      {
        type: 'laser',
        x: cx(40),
        y: cy(10),
        w: 20,
        h: cy(75),
        delay: 150,
      },
      { type: 'platform', x: cx(45), y: cy(57), w: cx(8), h: 40 },
      {
        type: 'movingEnemy',
        x: cx(58),
        y: cy(50),
        w: 60,
        h: 60,
        range: cx(14),
        speed: 150,
      },
      { type: 'spikes', x: cx(68), y: cy(92), count: 6, size: 40 },
      {
        type: 'laser',
        x: cx(75),
        y: cy(10),
        w: 20,
        h: cy(65),
        delay: 750,
      },
      { type: 'platform', x: cx(80), y: cy(35), w: cx(15), h: 40 },
    ],
  },

  {
    id: 15,
    name: "Icarus' Ultimatum",
    description: 'The final challenge. Fly carefully.',
    start: { x: cx(10), y: cy(80) },
    goal: { x: cx(85), y: cy(20) },
    obstacles: [
      { type: 'platform', x: cx(5), y: cy(88), w: cx(10), h: 40 },
      { type: 'spikes', x: cx(17), y: cy(92), count: 8, size: 40 },
      { type: 'platform', x: cx(23), y: cy(75), w: cx(8), h: 40 },
      {
        type: 'laser',
        x: cx(36),
        y: cy(8),
        w: 20,
        h: cy(77),
        delay: 0,
      },
      { type: 'platform', x: cx(41), y: cy(62), w: cx(7), h: 40 },
      {
        type: 'movingEnemy',
        x: cx(52),
        y: cy(55),
        w: 60,
        h: 60,
        range: cx(10),
        speed: 170,
      },
      { type: 'lava', x: cx(60), y: cy(88), w: cx(12), h: cy(12) },
      {
        type: 'laser',
        x: cx(64),
        y: cy(8),
        w: 20,
        h: cy(70),
        delay: 600,
      },
      { type: 'platform', x: cx(69), y: cy(48), w: cx(7), h: 40 },
      { type: 'spikes', x: cx(78), y: cy(92), count: 5, size: 40 },
      { type: 'platform', x: cx(82), y: cy(25), w: cx(13), h: 40 },
    ],
  },
];
